/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class ConfirmaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfirmaCliente
     */
    public ConfirmaCliente() {
        initComponents();
    }
    Venda venda = new Venda();
    
    public Venda getVenda(){
        return venda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pegaCPFvaiVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botarIrvenda = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setClosable(true);

        jLabel2.setText("Digite o CPF do cliente.");

        botarIrvenda.setText("Ir para a venda");
        botarIrvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botarIrvendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botarIrvenda))
                            .addComponent(pegaCPFvaiVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegaCPFvaiVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botarIrvenda)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botarIrvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botarIrvendaActionPerformed
        // TODO add your handling code here:
        if(pegaCPFvaiVenda.getText().equalsIgnoreCase("123456")){
            venda.setVisible(true);
            this.dispose();
        }else{
            if(JOptionPane.showConfirmDialog(null, "CLIENTE NAO CADASTRADO\nDESEJA SAIR?", "Responda",JOptionPane.YES_NO_CANCEL_OPTION) == 0){
                this.dispose();
            }else{
                pegaCPFvaiVenda.setText("");
            }
        }
        
        /*MenuGerente mn = new MenuGerente();
        mn.getPainelInteracao().add(new Venda());
        mn.getPainelInteracao().setVisible(true);
        new Venda().setVisible(true);*/
        
        
                
                
        
       
       
        
    }//GEN-LAST:event_botarIrvendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botarIrvenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pegaCPFvaiVenda;
    // End of variables declaration//GEN-END:variables
}
