/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabriel
 */
public class ListarPorCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form listarProdutosCadastrados
     */
    public ListarPorCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaExibirCategorias = new javax.swing.JTextArea();
        checkBebidas = new javax.swing.JCheckBox();
        checkCarnes = new javax.swing.JCheckBox();
        checkCereais = new javax.swing.JCheckBox();
        checkHigiene = new javax.swing.JCheckBox();
        checkLeiteDerivados = new javax.swing.JCheckBox();
        checkLimpeza = new javax.swing.JCheckBox();
        botaoListarCategoria = new javax.swing.JButton();
        informar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Selecione a categoria:");

        areaExibirCategorias.setColumns(20);
        areaExibirCategorias.setRows(5);
        areaExibirCategorias.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                areaExibirCategoriasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(areaExibirCategorias);

        checkBebidas.setText("Bebidas");

        checkCarnes.setText("Carnes");

        checkCereais.setText("Cereais");

        checkHigiene.setText("Higiene");

        checkLeiteDerivados.setText("Leite e Derivados");

        checkLimpeza.setText("Limpeza");

        botaoListarCategoria.setText("Listar");
        botaoListarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkCarnes)
                            .addComponent(checkBebidas))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkHigiene)
                            .addComponent(checkLimpeza))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkLeiteDerivados)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkCereais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addComponent(botaoListarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(informar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkLeiteDerivados)
                            .addComponent(checkBebidas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoListarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkCarnes)
                            .addComponent(checkCereais)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkHigiene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkLimpeza)))
                .addGap(10, 10, 10)
                .addComponent(informar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarCategoriaActionPerformed
        // TODO add your handling code here:
        informar.setText("Produtos por categoria: ");
    }//GEN-LAST:event_botaoListarCategoriaActionPerformed

    private void areaExibirCategoriasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_areaExibirCategoriasAncestorAdded
        // TODO add your handling code here:
        areaExibirCategorias.setText("teste");
    }//GEN-LAST:event_areaExibirCategoriasAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaExibirCategorias;
    private javax.swing.JButton botaoListarCategoria;
    private javax.swing.JCheckBox checkBebidas;
    private javax.swing.JCheckBox checkCarnes;
    private javax.swing.JCheckBox checkCereais;
    private javax.swing.JCheckBox checkHigiene;
    private javax.swing.JCheckBox checkLeiteDerivados;
    private javax.swing.JCheckBox checkLimpeza;
    private javax.swing.JLabel informar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
