/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import FuncaoFuncionario.FuncaoVendedor;
import javax.swing.JTextArea;

/**
 *
 * @author Gabriel
 */
public class ListarProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarProdutos
     */
    public ListarProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        escritaProdutosCadastrados = new javax.swing.JTextArea();
        botaoListarProdutos = new javax.swing.JButton();
        produtosnoestoque = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Listar Produtos no Estoque");

        escritaProdutosCadastrados.setColumns(20);
        escritaProdutosCadastrados.setRows(5);
        escritaProdutosCadastrados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                escritaProdutosCadastradosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(escritaProdutosCadastrados);

        botaoListarProdutos.setText("Listar");
        botaoListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(produtosnoestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtosnoestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarProdutosActionPerformed
        produtosnoestoque.setText("Produtos no estoque: ");
        FuncaoVendedor func = new FuncaoVendedor();
        escritaProdutosCadastrados.setText(func.listarProdutosCadastrados());
        
        
        
    }//GEN-LAST:event_botaoListarProdutosActionPerformed

    private void escritaProdutosCadastradosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_escritaProdutosCadastradosAncestorAdded
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_escritaProdutosCadastradosAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoListarProdutos;
    private javax.swing.JTextArea escritaProdutosCadastrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel produtosnoestoque;
    // End of variables declaration//GEN-END:variables
}
