/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Entidades.Loja;
import FuncaoFuncionario.FuncaoVendedor;

/**
 *
 * @author Gabriel
 */
public class ListarProdutosDisponiveis extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarProdutosDisponiveis
     */
    public ListarProdutosDisponiveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listedeProdutosNoEstoque = new javax.swing.JTextArea();
        listarProdutosemEstoqueBotao = new javax.swing.JButton();
        mostraEstoque = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Listar Produtos Disponiveis");

        listedeProdutosNoEstoque.setColumns(20);
        listedeProdutosNoEstoque.setRows(5);
        jScrollPane1.setViewportView(listedeProdutosNoEstoque);

        listarProdutosemEstoqueBotao.setText("Listar Produtos");
        listarProdutosemEstoqueBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutosemEstoqueBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mostraEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(listarProdutosemEstoqueBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listarProdutosemEstoqueBotao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostraEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarProdutosemEstoqueBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutosemEstoqueBotaoActionPerformed
        // TODO add your handling code here:
        mostraEstoque.setText("Produtos em estoque:");
        FuncaoVendedor func = new FuncaoVendedor();

        listedeProdutosNoEstoque.setText(func.ListarProdutosDisponiveis());
        
    }//GEN-LAST:event_listarProdutosemEstoqueBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarProdutosemEstoqueBotao;
    private javax.swing.JTextArea listedeProdutosNoEstoque;
    private javax.swing.JLabel mostraEstoque;
    // End of variables declaration//GEN-END:variables
}
