/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class MenuGerente extends javax.swing.JFrame {

    /** Creates new form MenuGerente */
    public MenuGerente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInteracao = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        botaoiniciaVenda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        cadastraClienteInterface = new javax.swing.JMenuItem();
        ListarClienteInterface = new javax.swing.JMenuItem();
        MenuExcluiCliente = new javax.swing.JMenuItem();
        MenuProdutos = new javax.swing.JMenu();
        MenuCadastraProduto = new javax.swing.JMenuItem();
        listaprodutosDispoiniveis = new javax.swing.JMenuItem();
        listarCategoriaInterface = new javax.swing.JMenuItem();
        ListarPromocoesInterface = new javax.swing.JMenuItem();
        ListarProdutos = new javax.swing.JMenuItem();
        MenuListaExcluidos = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        menu = new javax.swing.JMenu();
        ListarComprasDeUmaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Gerente");
        setResizable(false);

        painelInteracao.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APERTE O BOTAO ABAIXO PARA INICIAR UMA VENDA");

        botaoiniciaVenda.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botaoiniciaVenda.setText("INICIAR VENDA");
        botaoiniciaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoiniciaVendaActionPerformed(evt);
            }
        });

        painelInteracao.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelInteracao.setLayer(botaoiniciaVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelInteracaoLayout = new javax.swing.GroupLayout(painelInteracao);
        painelInteracao.setLayout(painelInteracaoLayout);
        painelInteracaoLayout.setHorizontalGroup(
            painelInteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInteracaoLayout.createSequentialGroup()
                .addGroup(painelInteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInteracaoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(painelInteracaoLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(botaoiniciaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        painelInteracaoLayout.setVerticalGroup(
            painelInteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInteracaoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(botaoiniciaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        Arquivo.setText("Arquivo");
        Arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivoActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Arquivo.add(Sair);

        jMenuBar1.add(Arquivo);

        MenuClientes.setText("Clientes");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });

        cadastraClienteInterface.setText("Cadastrar  cliente");
        cadastraClienteInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraClienteInterfaceActionPerformed(evt);
            }
        });
        MenuClientes.add(cadastraClienteInterface);

        ListarClienteInterface.setText("Listar clientes");
        ListarClienteInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteInterfaceActionPerformed(evt);
            }
        });
        MenuClientes.add(ListarClienteInterface);

        MenuExcluiCliente.setText("Excluir cliente");
        MenuExcluiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExcluiClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(MenuExcluiCliente);

        jMenuBar1.add(MenuClientes);

        MenuProdutos.setText("Produtos");

        MenuCadastraProduto.setText("Cadastrar Produto");
        MenuCadastraProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastraProdutoActionPerformed(evt);
            }
        });
        MenuProdutos.add(MenuCadastraProduto);

        listaprodutosDispoiniveis.setText("Listar Produtos Disponiveis");
        listaprodutosDispoiniveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaprodutosDispoiniveisActionPerformed(evt);
            }
        });
        MenuProdutos.add(listaprodutosDispoiniveis);

        listarCategoriaInterface.setText("Listar produtos por categoria");
        listarCategoriaInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCategoriaInterfaceActionPerformed(evt);
            }
        });
        MenuProdutos.add(listarCategoriaInterface);

        ListarPromocoesInterface.setText("Listar promocoes");
        ListarPromocoesInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPromocoesInterfaceActionPerformed(evt);
            }
        });
        MenuProdutos.add(ListarPromocoesInterface);

        ListarProdutos.setText("Listar produtos cadastrados");
        ListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProdutosActionPerformed(evt);
            }
        });
        MenuProdutos.add(ListarProdutos);

        MenuListaExcluidos.setText("Listar Produtos Excluidos");
        MenuListaExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListaExcluidosActionPerformed(evt);
            }
        });
        MenuProdutos.add(MenuListaExcluidos);

        jMenuBar1.add(MenuProdutos);

        MenuSobre.setText("Sobre");
        jMenuBar1.add(MenuSobre);

        menu.setText("Venda");

        ListarComprasDeUmaVenda.setText("Listar compras de uma venda");
        menu.add(ListarComprasDeUmaVenda);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelInteracao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelInteracao)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        
        if (JOptionPane.showConfirmDialog(null, "Deseja sair?", "Responda",JOptionPane.YES_NO_CANCEL_OPTION) == 0){
            this.dispose();
        }

    }//GEN-LAST:event_SairActionPerformed

    private void ArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ArquivoActionPerformed

    private void cadastraClienteInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraClienteInterfaceActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente cadastroCliente = new TelaCadastroCliente();    // TELA DE CADASTRO DE CLIENTE
        painelInteracao.add(cadastroCliente);
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_cadastraClienteInterfaceActionPerformed

    private void ListarClienteInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteInterfaceActionPerformed
        // TODO add your handling code here:
        ListarClientes listacli = new ListarClientes();
        painelInteracao.add(listacli);
        listacli.setVisible(true);

    }//GEN-LAST:event_ListarClienteInterfaceActionPerformed

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuClientesActionPerformed

    private void listarCategoriaInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCategoriaInterfaceActionPerformed
        // TODO add your handling code here:
        ListarPorCategoria lcateg = new ListarPorCategoria();
        painelInteracao.add(lcateg);
        lcateg.setVisible(true);
    }//GEN-LAST:event_listarCategoriaInterfaceActionPerformed

    private void ListarPromocoesInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPromocoesInterfaceActionPerformed
        // TODO add your handling code here:
        ListarPromocoes listapromo = new ListarPromocoes();
        painelInteracao.add(listapromo);
        listapromo.setVisible(true);
    }//GEN-LAST:event_ListarPromocoesInterfaceActionPerformed

    private void ListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProdutosActionPerformed
        // TODO add your handling code here:
        ListarProdutos lp = new ListarProdutos();
        painelInteracao.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_ListarProdutosActionPerformed

    private void botaoiniciaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoiniciaVendaActionPerformed
        // TODO add your handling code here:
        ConfirmaCliente conf = new ConfirmaCliente();
        painelInteracao.add(conf);
        conf.setVisible(true);
        painelInteracao.add(conf.getVenda());
    }//GEN-LAST:event_botaoiniciaVendaActionPerformed

    private void MenuExcluiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExcluiClienteActionPerformed
        // TODO add your handling code here:
        ExcluirCliente exclu = new ExcluirCliente();
        painelInteracao.add(exclu);
        exclu.setVisible(true);
    }//GEN-LAST:event_MenuExcluiClienteActionPerformed

    private void MenuCadastraProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastraProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto cadprod = new CadastrarProduto();
        painelInteracao.add(cadprod);
        cadprod.setVisible(true);
    }//GEN-LAST:event_MenuCadastraProdutoActionPerformed

    private void MenuListaExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListaExcluidosActionPerformed
        // TODO add your handling code here:
        ListarProdutosExcluidos lpe = new ListarProdutosExcluidos();
        painelInteracao.add(lpe);
        lpe.setVisible(true);
    }//GEN-LAST:event_MenuListaExcluidosActionPerformed

    private void listaprodutosDispoiniveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaprodutosDispoiniveisActionPerformed
        // TODO add your handling code here:
        ListarProdutosDisponiveis lpd = new ListarProdutosDisponiveis();
        painelInteracao.add(lpd);
        lpd.setVisible(true);
    }//GEN-LAST:event_listaprodutosDispoiniveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
                
                
                
            }
        });
    }
    public JDesktopPane getPainelInteracao(){
        return painelInteracao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenuItem ListarClienteInterface;
    private javax.swing.JMenuItem ListarComprasDeUmaVenda;
    private javax.swing.JMenuItem ListarProdutos;
    private javax.swing.JMenuItem ListarPromocoesInterface;
    private javax.swing.JMenuItem MenuCadastraProduto;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuItem MenuExcluiCliente;
    private javax.swing.JMenuItem MenuListaExcluidos;
    private javax.swing.JMenu MenuProdutos;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JButton botaoiniciaVenda;
    private javax.swing.JMenuItem cadastraClienteInterface;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaprodutosDispoiniveis;
    private javax.swing.JMenuItem listarCategoriaInterface;
    private javax.swing.JMenu menu;
    private javax.swing.JDesktopPane painelInteracao;
    // End of variables declaration//GEN-END:variables

}
